### ISSUE TITLE
Live or concluded CFB games incorrectly showing `"gameState": "pre"` with empty scores

### ISSUE THREAD

**Issue by r-token** [henrygd/ncaa-api#11]
The `/scoreboard/football/fbs` endpoint is returning some (all?) live or concluded games with `"gameState": "pre"` and empty score strings (`"score": ""`), even when those games are currently being played or are already over.

## Expected Behavior
Live games should have:
- `gameState: "live"` 
- Current scores as non-empty strings (e.g., `"score": "14"`)
- Appropriate `currentPeriod` reflecting the actual game period

## Actual Behavior
Some games that are currently live or already over are showing:
- `gameState: "pre"`
- `"score": ""` for both teams
- `currentPeriod: ""` or outdated period information

## Example
The Ohio St vs. Texas game is over, yet this is the response from the API as of 3:42 PM ET on Sat, August 30:
```
{
      "game": {
        "gameID": "43463",
        "away": {
          "score": "",
          "names": {
            "char6": "TEXAS",
            "short": "Texas",
            "seo": "texas",
            "full": "University of Texas at Austin"
          },
          "winner": false,
          "seed": "",
          "description": "(0-0)",
          "rank": "1",
          "conferences": [
            {
              "conferenceName": "SEC",
              "conferenceSeo": "sec"
            },
            {
              "conferenceName": "Top 25",
              "conferenceSeo": "top-25"
            }
          ]
        },
        "finalMessage": "",
        "bracketRound": "",
        "title": "Ohio St. Texas",
        "contestName": "",
        "url": "/game/6459545",
        "network": "",
        "home": {
          "score": "",
          "names": {
            "char6": "OHIOST",
            "short": "Ohio St.",
            "seo": "ohio-st",
            "full": "The Ohio State University"
          },
          "winner": false,
          "seed": "",
          "description": "(0-0)",
          "rank": "3",
          "conferences": [
            {
              "conferenceName": "Big Ten",
              "conferenceSeo": "big-ten"
            },
            {
              "conferenceName": "Top 25",
              "conferenceSeo": "top-25"
            }
          ]
        },
        "liveVideoEnabled": false,
        "startTime": "12:00PM ET",
        "startTimeEpoch": "1756569600",
        "bracketId": "",
        "gameState": "pre",
        "startDate": "08-30-2025",
        "currentPeriod": "",
        "videoState": "",
        "bracketRegion": "",
        "contestClock": ""
      }
    }
```

## Impact
This prevents applications from:
- Detecting when games have started
- Tracking live score changes
- Triggering events based on game state transitions

## Reproduction
1. Call `GET https://ncaa-api.henrygd.me/scoreboard/football/fbs`
2. Check games that are currently being played
3. Observe that some show `gameState: "pre"` despite being in progress or being over

## Environment
- Endpoint: `https://ncaa-api.henrygd.me/scoreboard/football/fbs`
- Date observed: August 30, 2025

This appears to be a data synchronization issue where the API isn't updating game states from the upstream NCAA data source in real-time. Let me know if you need any additional information.

**Comment by henrygd** [comment]
Looks like they may have changed something upstream. I'll look into it when possible but may not be able until tomorrow.

**Comment by henrygd** [comment]
No need but that's very kind, thanks. I pushed  a quick update to hopefully fix it for football today. Can you check if it looks okay on your end?

**Comment by r-token** [comment]
No dice, unfortunately. Florida State vs. Alabama is going on right now, for example, and I'm still seeing `"gameState": "pre"` and `"score": ""` for both teams when hitting `GET https://ncaa-api.henrygd.me/scoreboard/football/fbs/`

**Comment by henrygd** [comment]
Sorry I fixed it for `/scoreboard/football/fbs/2025/01/all-conf` but not `/scoreboard/football/fbs`. Please try again, it should show now.

**Comment by r-token** [comment]
That did it! Thank you! Sent you some coffees ☕️

**Comment by henrygd** [comment]
Gracias, glad it works! Figures they'd switch their system around as football starts.

Football *should* continue to work this season unless anything else changes. I'll try to fix other sports as time allows.

**Comment by henrygd** [comment]
FYI, checked today and the old method I used to detect the correct week / date is no longer working. So `/scoreboard/football/fbs` always returns week one scores.

But `/scoreboard/football/fbs/2025/02` and `/scoreboard/football/fbs/2025/02/all-conf` does work as intended. I'll look for an alternative but wanted to give you and anyone checking a heads up.
